cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns=[
	url(r'^$', views.Detalle.as_view(),name="cart_detail"),
	url(r'^add/(?P<pk>\d+)/$', views.Agregar.as_view(), name="cart_add"),
	url(r'^remove/(?P<pk>\d+)/$', views.Remove.as_view(), name="cart_remove")
	
]

projects/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	
	url(r'^json/(?P<pk>\d+)/$',
		views.JsonRewards.as_view(),
		name="json_rewards"),

	url(r'^explorar/(?P<cat>[-\w]+)/$',
		views.Explorar.as_view(),
		name="categoria"),

	url(r'^explorar/$',
		views.Explorar.as_view(),
		name="explorar"),

	url(r'^new/$',
		views.NewProject.as_view(),
		name="new"),
    
    url(r'^(?P<pk>\d+)/$', 
    	views.DetailProject.as_view(), 
    	name='detail'),
    
    url(r'^$', 
    	views.Projects.as_view(), 
    	name='list'),
    ]

retozapopan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import urls as accountsURLs
from social.apps.django_app import urls as socialURLs
# from social_django import urls as socialURLs
from main import urls as mainUrls
from inputs import urls as inputsURLs
from dashboard import urls as dashboardURLs
from projects import urls as projectsURLs
from cart import urls as cartURLs

from django.views.static import serve
from django.conf import settings


urlpatterns = [

    #main
    url(r'^', include(mainUrls)),

    url(r'^inputs/',
        include(inputsURLs)),

    url(r'^dashboard/',
        include(dashboardURLs, namespace="dash")),

    url(r'^projects/',
        include(projectsURLs, namespace="projects")),

    url(r'^accounts/',
        include(accountsURLs)),

    url(r'^cart/',
        include(cartURLs, namespace="cart")),

    #Django Admin
    url(r'^admin/', admin.site.urls),

    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs={'document_root':settings.MEDIA_ROOT}
        ),

    # Social Auth
    url('social-auth/',
        include(socialURLs,
            namespace="social")),

]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.urls import reverse
#django 1.9:
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager



class Project(models.Model):

    name = models.CharField(max_length=250)
    desc = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, related_name="projects", blank=True, null=True)
    goal = models.CharField(max_length=140)
    date = models.DateTimeField(auto_now=True, blank=True, null=True)
    img = models.ImageField(upload_to="projects/images", blank=True, null=True)
    video = models.CharField(max_length=500, blank=True,null=True)
    publish = models.BooleanField(default=False)
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('dash:detail', kwargs={'pk':self.pk})

    def get_absolute_url_public(self):
        return reverse('projects:detail', args=[self.pk])

    def __str__(self):
        return self.name

class Reward(models.Model):

    project = models.ForeignKey(Project, related_name='rewards')
    title = models.CharField(max_length=250)
    price = models.DecimalField(decimal_places=2,max_digits=10)
    desc = models.TextField()
    quantity = models.IntegerField()
    deliver_date = models.DateField()
    buyers = models.ManyToManyField(User, related_name='buyers')

    class Meta:
        ordering = ['price']

    def __str__(self):
        return self.title


class Comments(models.Model):
    user = models.ForeignKey(User, related_name='comments')
    comment = models.TextField()
    date = models.DateTimeField(auto_now=True)

class Image(models.Model):
    img = models.ImageField(upload_to="projects/images")
    project = models.ForeignKey(Project,related_name="images")

class NewProject(models.Model):
    name = models.CharField(max_length=250, blank=True, null=True)
    goal = models.DecimalField(max_digits=7, decimal_places=2, default=1, blank=True, null=True)

projects/forms.py
from django import forms
from .models import Project


class NewProjectForm(forms.ModelForm):
	class Meta:
		model = Project
		fields = ['name','goal','user']

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.views.generic import View
from django.views.generic import ListView

from .models import Project, Reward

from .forms import NewProjectForm

from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.core import serializers

from taggit.models import Tag



class Explorar(ListView):
	template_name = "projects/explorar.html"
	# queryset = Project.objects.all()
	context_object_name = 'projects'
	paginate_by = 6
	

	def get_queryset(self):
		try:
			tag = get_object_or_404(Tag, slug=self.kwargs['cat'])
			return Project.objects.all().filter(tags__in=[tag])
		except:
			return Project.objects.all()


	def get_context_data(self, **kwargs):
		context = super(Explorar, self).get_context_data(**kwargs)
		context['nav_section'] = "explorar"
		try:
			tag = get_object_or_404(Tag, slug=self.kwargs['cat'])
			context['categoria'] = tag
		except:
			pass
		return context



class NewProject(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name="projects/new.html"
		context = {
			'nav_section':'new'
		}
		return render(request, template_name, context)


	def post(self, request):
		form = NewProjectForm(request.POST)
		if form.is_valid():
			np = form.save(commit=False)
			np.user = request.user
			np.save()
			messages.success(request,"Tu proyecto fué creado con éxito")
			return redirect('dash:dash')
		else:
			messages.error(request,"Algo malo pasó U_U intentalo de nuevo")
			return redirect('projects:new')






class Projects (View):
	def get(self, request):
		
		template_name= 'projects.html'
		projects = Project.objects.all()
		context = {
		'projects':projects
		}

		

		return render(request, template_name, context )


import markdown2
from markdown2 import Markdown


class DetailProject(View):
	def get(self,request,pk):
		template_name = 'projects/detail.html'
		##obejto project
		project = get_object_or_404(Project, id = pk)
		markdowner = Markdown()
		# project.desc = markdown2.markdown(project.desc)
		try:
			project.desc = markdowner.convert(project.desc)
		except:
			pass

		context = {
			'project':project,
		}

		return render(request, template_name, context)


class JsonRewards(View):
	def get(self, request, pk):
		r = get_object_or_404(Reward, id=pk)
		data = serializers.serialize('json',[r],indent=2,
			use_natural_foreign_keys=False, use_natural_primary_keys=False)
		return HttpResponse(data,content_type = 'application/javascript; charset=utf8') 

projects/templates/projects/detail.html
{%extends 'base.html'%}


{%block content%}

<section class="contenedor well well-sm">

<div class="centrado">
	<h2>{{project.name}}</h2>
	<a class="btn btn-info btn-xs" type="button">
		<span class="fui-calendar"></span>
		{{project.date | date:"d, M Y"}}
	</a>
	{%for t in project.tags.all%}
	<a href="{%url 'projects:categoria' t.slug%}" class="btn btn-info btn-xs" type="button">
		<span class="fui-tag"></span>
		{{t.name}}
	</a>
	{%endfor%}
	
</div>
<br>
<article class="row panel-body">


<div style="height:auto;" class="col-sm-8">

	{%if project.video%}
	<iframe id="vidPrev" width="100%" height="508" src="{{project.video}}" frameborder="0" allowfullscreen></iframe>
	{%else%}
		{%if project.img%}
			<img class="img-responsive" src="{{project.img.url}}">
		{%else%}
			<img class="img-responsive" src="http://www.ciiecca.org.ar/wp-content/themes/openmind/img/no_image.png">
		{%endif%}
	{%endif%}
</div>

<div class="col-sm-4 panel">

	<div class="user row panel-body">
		<div class="col-xs-3">
			{%if project.user.profile.img%}
			<img class="foto_perfil" src="{{project.user.profile.img.url}}">
			{%endif%}
		</div>
		<div class="col-xs-9">
			<span>{{project.user.first_name}} {{project.user.last_name}}</span>
			<div class="divider"></div>
			<a href="mailto:{{project.user.email}}">{{project.user.email}}</a>
		</div>
	</div>
	<br>
	<div class="patrocinadores">
		<h4 style="margin:0">15</h4>
		<span>Patrocinadores</span>
	</div>
	<div class="dinero">
		<h4 class="text-success" style="margin:0">$350 MXN</h4>
		<span>De la meta de ${{project.goal}}</span>
		<div class="progress">
			<div class="progress-bar" style="width: 40%;"></div>
		</div>
	</div>
	<div class="fechas">
		<h4 class="text-danger" style="margin:0">30</h4>
		<span>Días restantes</span>
	</div>
	<br>
	<div class="cart">
		<button class="btn btn-success">
			Patrocinar este proyecto
		</button>
	</div>



		<div class="social panel-body">
		<div class="icon" data-toggle="tooltip" data-placement="bottom" title="Comparte en Facebook">
			<span class="fui-facebook"></span>
		</div>
		<div class="icon" data-toggle="tooltip" data-placement="bottom" title="Comparte en Twitter">
			<span class="fui-twitter"></span>
		</div>
		<div class="icon" data-togle="tooltip" data-placement="bottom" title="Comparte en Pinterest">
			<span class="fui-pinterest"></span>
		</div>
		<div class="icon" data-toggle="tooltip" data-placement="bottom" title="Copia el link">
			<span class="fui-link"></span>
		</div>
	</div>

</div>


</article> <!-- row-->

</section>

<br>

<section class="acerca contenedor">

	<article class="row">


		<div class="desc col-md-8 well">

			{%autoescape off%}{{project.desc}}{%endautoescape%}

		</div>

		<div class="rewards col-md-4">

			 {%for r in project.rewards.all%}
			
			<form action="{%url 'cart:cart_add' r.pk%}" method="post">
			
				{%csrf_token%}
				<input type="hidden" name="quantity" value="1">
				<input type="hidden" name="update" value="false">

			<div class="well reward">
				<p>Contribuir: </p>
				<h6><span class="dineros" >$</span>{{r.price}}MXN</h6>
				<h5>{{r.title}}</h5>
				<p>{{r.desc}}</p>
				<span class="dineros">Fecha aproximada de entrega: <span class="text-info">{{r.deliver_date|date:"M, Y"}}</span></span>
				<br>
				<span class="dineros">608 <span class="text-info">Adquiridos</span></span>
				<div class="selected">Obtener esta recompensa</div>
			</div>
			</form>

			{%endfor%}


		</div>






	</article>





</section>



















	

<script>
	$('[data-toggle="tooltip"]').tooltip()

	$('form').on('click',function(){
		$(this).submit();
	});

	$('img').addClass('img-responsive');
</script>
{%endblock content%}

projects/templates/projects/explorar.html
{%extends 'base.html'%}

{%block content%}

<section class="">

<div class="centrado img_fondo text-blanco"
{%if categoria.name == 'Comunidad'%}
style="background-image:url('http://www.nuevogramalote.com/joomla/images/noticia_1.JPG');"
{%endif%}
{%if categoria.name == 'Medio Ambiente'%}
style="background-image:url('https://userscontent2.emaze.com/images/38423a3f-4237-4fb0-a8a2-e8bef05ba6e2/372eb8a200ad5dca3e2780d3df29f9ff.jpg');"
{%endif%}
>
	<div class="pantalla">
  	<!-- categoria-->
	{%if not categoria%}
	<h2>Explorar proyectos</h2>
	  <p>Stay fit and healthy with these campaigns for your physical, emotional and mental wellbeing.</p>
	{%else%}
	<h3>{{categoria}}</h3>
  <p>Stay fit and healthy with these campaigns for your physical, emotional and mental wellbeing.</p>
	{%endif%}

	</div>

</div>
<div class="panel centrado">
	<h3>
<!-- 	<span>Numero de proyectos</span>
	<span>Numero de dinero recaudad</span>
	<span>Otro dato</span> -->
	</h3>
</div>

		<!-- paginator -->




<article class="row">

<div class="col-lg-3 col-md-4">

			<div class="fondo_oficial">
			
			<div class="seccion panel-body">
				<h5>Categorías</h5>
				<div class="row">

          <a href="{%url 'projects:categoria' 'tecnologia'%}">
					<div style="padding:10px" class="col-xs-6 centrado">
					<div {%if categoria.name == 'Tecnología'%} class="exp active" {%else%} class="exp" {%endif%} >
						<i class="fa fa-cogs" aria-hidden="true"></i></i><br>
						<span>Tecnología</span>

					</div>
					</div>
          </a>

					<a href="{%url 'projects:categoria' 'comunidad'%}">
          <div style="padding:10px" class="col-xs-6 centrado">
          <div class="exp {%if categoria.name == 'Comunidad'%} active {%endif%}">
            <i class="fa fa-users" aria-hidden="true"></i>
            <br>
            <span>Comunidad</span>

          </div>
          </div>
          </a>

					<a href="{%url 'projects:categoria' 'medio-ambiente'%}">
          <div style="padding:10px" class="col-xs-6 centrado">
          <div class="exp {%if categoria.name == 'Medio Ambiente'%} active {%endif%}">
            <i class="fa fa-pagelines" aria-hidden="true"></i>
            <br>
            <span>Medio Ambiente</span>

          </div>
          </div>
          </a>

          <a href="{%url 'projects:categoria' 'arte'%}">
          <div style="padding:10px" class="col-xs-6 centrado">
          <div class="exp {%if categoria.name == 'Arte'%} active {%endif%}">
            <i class="fa fa-paint-brush" aria-hidden="true"></i>
            <br>
            <span>Arte</span>

          </div>
          </div>
          </a>

          <a href="{%url 'projects:categoria' 'diseno'%}">
          <div style="padding:10px" class="col-xs-6 centrado">
          <div class="exp {%if categoria.name == 'Diseño'%} active {%endif%}">
            <i class="fa fa-ravelry" aria-hidden="true"></i>
            <br>
            <span>Diseño</span>

          </div>
          </div>
          </a>

          <a href="{%url 'projects:categoria' 'educacion'%}">
          <div style="padding:10px" class="col-xs-6 centrado">
          <div class="exp {%if categoria.name == 'Educación'%} active {%endif%}">
            <i class="fa fa-graduation-cap" aria-hidden="true"></i>
            <br>
            <span>Educación</span>

          </div>
          </div>
          </a>


				</div>
			</div>
			<div class="divider1"></div>
			<div class="seccion panel-body">
				<h5>Areas</h5>
				<ul>
					<li>
						<a href>Area</a>
					</li>
					<li>
						<a href>Area</a>
					</li>
					<li>
						<a href>Area</a>
					</li>
				</ul>
			</div>
			<div class="divider1"></div>
			<div class="seccion panel-body">
				<h5>Destacado</h5>
				<ul>
					<li>
						<a href>más vistos</a>
					</li>
					<li>
						<a href>más fondeados</a>
					</li>
					<li>
						<a href>más populares</a>
					</li>
				</ul>
			</div>
			
		</div>
		</div> <!-- selector-->



<div class="col-lg-9 col-md-8 row">




{%for p in projects%}

<div class="col-sm-6 col-lg-4">
  <a href="{{p.get_absolute_url_public}}">
      <div class=" tarjeta">
        <div class="card-section tagpadre">
          <span class='boxed'>{{p.tags.all|join:", "}}</span>
          {%if p.img%}
          <img class='proyect' src="{{p.img.url}}">
          {%else%}
          <img class='proyect' src="https://images.pexels.com/photos/8704/pen-idea-bulb-paper.jpg?w=1260&h=750&auto=compress&cs=tinysrgbg">
          {%endif%}

          <p class='titulo'>{{p.name}}</p>
        </div>
        <div class='datos'>
          <div style='display:inline-flex;'>
            <div>
              <img class='foto_perfil' src="https://scontent.fmex5-1.fna.fbcdn.net/v/t1.0-9/10610561_661134757315249_1937519055020262032_n.jpg?oh=5e2983bea71a5b7d1923ff6be03dd25d&oe=58F864C3">
            </div>
            <div style='text-align:left;' class='apodo'>
              <p style='margin-bottom:0px'>{{p.user.username}}</p>
              <p>Zapopan, Jalisco</p>
            </div>
          </div>
          <div class='resumen'>
           <!-- {# <p>{{p.desc | truncatewords:30}}</p> #} -->
          </div>
          <div class="progress">
            <div class="progress-bar" style="width: 40%;"></div>
            <div class="progress-bar progress-bar-warning" style="width: 60%;"></div>
          </div>
          <div>
            <span class='dineros'>Meta: ${{p.goal}}</span>
            <span class='fin'>Finaliza:11/Feb/17</span>
          </div>
        </div> 
      </div> 
  </a>
</div> <!-- card-->

{%endfor%}




</div> <!-- col-->


<div class="centrado col-sm-12">
{%include 'pagination.html' with page=page_obj%}
</div>
</article>








</section>




	
{%endblock content%}

projects/templates/projects/new.html
{%extends 'base.html'%}

{%block content%}

	<section class="contenedor centrado">
		<h3>¡Consigue fondos para tu gran proyecto!</h3>
		<br><br><br>
<form id="nuevo" class="row panel panel-default" action="." method="post">
	{%csrf_token%}
		<div class="col-md-6 col-md-offset-3 panel-body">

		<div class="row">
		<h4 class="col-md-12">
			¿Cómo se llama tu proyecto?
		</h4>
		<input name="name" required placeholder="Mi fabuloso proyecto" class="form-control input-hg col-md-12" type="text">
		</div>

		<div class="row">
		<h4 class="col-md-12">
			¿Cuanto dinero necesitas?
		</h4>
		<div class="input-group">
		  <span class="input-group-addon">$</span>
		  <input name="goal" required type="number" class="form-control input-hg" placeholder="200000" />
		</div>
		</div>
		<br>
		<input class="btn btn-hg btn-primary" type="submit" value="¡Lanzar mi proyecto!">

		</div> <!-- offset-->

</form>


	</section>

{%endblock content%}