cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns=[
	url(r'^$', views.Detalle.as_view(),name="cart_detail"),
	url(r'^add/(?P<pk>\d+)/$', views.Agregar.as_view(), name="cart_add"),
	url(r'^remove/(?P<pk>\d+)/$', views.Remove.as_view(), name="cart_remove")
	
]

dashboard/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

	url(r'^$',
		views.Dash.as_view(),
		name="dash"),

	url(r'^(?P<pk>\d+)/rewards/$',
		views.Rewards.as_view(),
		name="rewards"),

	url(r'^(?P<pk>\d+)/$',
		views.Detail.as_view(),
		name="detail"),

	url(r'^support/$',
		views.Support.as_view(),
		name="support"),

	url(r'^(?P<pk>\d+)/basics/$',
		views.Basics.as_view(),
		name="basics"),

	url(r'^(?P<pk>\d+)/history/$',
		views.History.as_view(),
		name="history"),

	url(r'^(?P<pk>\d+)/team/$',
		views.Team.as_view(),
		name="team"),

	url(r'^(?P<pk>\d+)/extra/$',
		views.Extra.as_view(),
		name="extra"),

	url(r'^chat/$',
		views.Chating.as_view(),
		name="chat"),
]

projects/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	
	url(r'^json/(?P<pk>\d+)/$',
		views.JsonRewards.as_view(),
		name="json_rewards"),

	url(r'^explorar/(?P<cat>[-\w]+)/$',
		views.Explorar.as_view(),
		name="categoria"),

	url(r'^explorar/$',
		views.Explorar.as_view(),
		name="explorar"),

	url(r'^new/$',
		views.NewProject.as_view(),
		name="new"),
    
    url(r'^(?P<pk>\d+)/$', 
    	views.DetailProject.as_view(), 
    	name='detail'),
    
    url(r'^$', 
    	views.Projects.as_view(), 
    	name='list'),
    ]

retozapopan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import urls as accountsURLs
from social.apps.django_app import urls as socialURLs
# from social_django import urls as socialURLs
from main import urls as mainUrls
from inputs import urls as inputsURLs
from dashboard import urls as dashboardURLs
from projects import urls as projectsURLs
from cart import urls as cartURLs

from django.views.static import serve
from django.conf import settings


urlpatterns = [

    #main
    url(r'^', include(mainUrls)),

    url(r'^inputs/',
        include(inputsURLs)),

    url(r'^dashboard/',
        include(dashboardURLs, namespace="dash")),

    url(r'^projects/',
        include(projectsURLs, namespace="projects")),

    url(r'^accounts/',
        include(accountsURLs)),

    url(r'^cart/',
        include(cartURLs, namespace="cart")),

    #Django Admin
    url(r'^admin/', admin.site.urls),

    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs={'document_root':settings.MEDIA_ROOT}
        ),

    # Social Auth
    url('social-auth/',
        include(socialURLs,
            namespace="social")),

]

dashboard/forms.py
from django import forms
from projects.models import Project, Reward
from accounts.models import Profile


class ImgForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['img','tel']

class BasicsForm(forms.ModelForm):
	class Meta:
		model = Project
		fields = ['name', 'goal','tags']

class HistoryForm(forms.ModelForm):
	class Meta:
		model = Project
		fields = ['desc','video','img']

class NewRewardForm(forms.ModelForm):
	class Meta:
		model = Reward
		fields = ['title','price','desc','quantity','deliver_date']

dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View

from projects.models import Project, Reward
from accounts.models import Profile
from .forms import BasicsForm, HistoryForm, ImgForm, NewRewardForm

from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from taggit.models import Tag

class Dash(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "dashboard/perfil.html"
		projects = request.user.projects.all()

		context = {
			'projects':projects
		}
		return render(request, template_name, context)

	def post(self, request):
		try:
			profile = request.user.profile
		except:
			profile = Profile()
			profile.user = request.user
			profile.save()

		form = ImgForm(instance=request.user.profile,data=request.POST, files=request.FILES)
		print(form)
		print(request.FILES)
		if form.is_valid():
			form.save()
			messages.success(request, "Tu Perfil se actualizó con exito")
		else:
			messages.error(request, "Algo malo pasó, U_U intenta de nuevo")
		return redirect('dash:dash')

class Detail(View):
	def get(self, request, pk):
		template_name = "dashboard/dash.html"
		p = get_object_or_404(Project, id=pk)
		context = {
			'project':p,
			'section':'dash'
		}
		return render(request, template_name,context)

class Basics(View):
	def get(self, request, pk):
		template_name = "dashboard/basics.html"
		p = get_object_or_404(Project, id=pk)
		form = BasicsForm()
		cats = Tag.objects.all()
		context = {
			'project':p,
			'section':'basics',
			'form':form,
			'cats':cats
		}
		return render(request, template_name,context)

	def post(self, request, pk):
		template_name = "dashboard/basics.html"
		p = get_object_or_404(Project, id=pk)
		if p.publish:
			messages.error(request, "Tu proyecto ya se publicó, no puedes modificarlo")
			return redirect('dash:basics',pk=pk)
		data = request.POST.dict()
		form = BasicsForm(data,request.FILES,instance=p)
		# print(form)

		if form.is_valid():
			form.save()
			print('PASO Y GUARDO')
			messages.success(request, "Proyecto guardado con éxito")
		else:
			print('No es Valido')

			messages.error(request, "El proyecto no se guardó")


		context = {
			'project':p,
			'section':'basics',
			'cats':Tag.objects.all()
			
		}
		return render(request, template_name,context)

import markdown2

class History(View):
	def get(self, request, pk):
		template_name = "dashboard/history.html"
		p = get_object_or_404(Project, id=pk)
		try:
			p.desc = markdown2.markdown(p.desc)
		except:
			pass
		context = {
			'project':p,
			'section':'history'
		}
		return render(request, template_name,context)

	def post(self, request, pk):
		template_name = "dashboard/history.html"
		p = get_object_or_404(Project, id=pk)
		data = request.POST.dict()
		form = HistoryForm(data, files=request.FILES,instance=p)
		print(form)
		# print(form)

		if form.is_valid():
			form.save()
			print('PASO Y GUARDO')
			messages.success(request, "Proyecto guardado con éxito")
		else:
			print('No es Valido')
			messages.error(request, "El proyecto no se guardó")

		context = {
			'project':p,
			'section':'history',
		}
		return render(request, template_name,context)


class Rewards(View):
	def get(self, request, pk):
		template_name = "dashboard/rewards.html"
		p = get_object_or_404(Project, id=pk)
		rewards = p.rewards.all()
		context = {
			'project':p,
			'section':'recompensas',
			'rewards':rewards
		}
		return render(request, template_name, context)

	def post(self, request, pk):

		if request.POST.get('borrar'):
			r = get_object_or_404(Reward, id=request.POST.get('borrar'))
			r.delete()
			messages.success(request, "Haz borrado una recompensa")
			return redirect('dash:rewards',pk=pk)

		p = get_object_or_404(Project, id=pk)

		form = NewRewardForm(data=request.POST)
		if request.POST.get('pk'):
			r = get_object_or_404(Reward,id=request.POST.get('pk'))
			form = NewRewardForm(data=request.POST, instance=r)
		
		if form.is_valid():
			r = form.save(commit=False)
			r.project = p
			r.save()
			messages.success(request, "Tu recompensa se ha guardado con éxito")
			
		else:
			messages.error(request, "Algo malo pasó, U_U vuelve a intentarlo")
		return redirect('dash:rewards',pk=pk)


class Team(View):
	def get(self, request, pk):
		template_name = "dashboard/basics.html"
		p = get_object_or_404(Project, id=pk)
		context = {
			'project':p,
			'section':'team'
		}
		return render(request, template_name,context)

class Extra(View):
	def get(self, request, pk):
		template_name = "dashboard/basics.html"
		p = get_object_or_404(Project, id=pk)
		context = {
			'project':p,
			'section':'extra'
		}
		return render(request, template_name,context)




# Panels del lado del que apoya incluyendo chat

class Support(View):
	def get(self, request):
		template_name = "dashboard/founder.html"
		p = request.user.funds.all()
		context = {
			'projects':p
		}
		return render(request, template_name, context)

class Chating(View):
	def get(self, request, pk=None):
		template_name = "dashboard/mensajeria.html"
		# project = get_object_or_404(Project,id=pk)
		p = request.user.funds.all()
		print(request.user.cchats.all())
		# chat = request.user.cchats.all().get(project=project)
		
		context = {
			'projects':p,
			# 'chat':chat
		}
		return render(request, template_name, context)

dashboard/templates/dashboard/basics.html
{%extends 'base.html'%}
{%load dash_tags%}

{%block content%}
{%count_projects as nums %}


<section class="contendor centrado">

	<h3 class="demo-panel-title">{{project}} / {{section}}</h3>

	<article class="row">

		<div class="col-md-3 col-md-offset-1">
			<div class="todo">
			
			<ul>

				<a class="no-link" href="{%url 'dash:detail' project.pk%}">
				<li>
					
					<div class="todo-icon fui-resize"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Dashboard</strong>
						</h4>
						¿Cómo va tu proyecto?
					</div>
					
				</li>
				</a>

				<a class="no-link" href="{%url 'dash:detail' project.pk%}">
				<li class="todo-done">
					
					<div class="todo-icon fui-eye"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Info Basica</strong>
						</h4>
						Empezamos por aquí
					</div>
					
				</li>
				</a>

				<a class="no-link" href="{%url 'dash:history' project.pk%}">
				<li>
					
					<div class="todo-icon fui-image"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Descripción</strong>
						</h4>
						Cuentanos tu historia
					</div>
					
				</li>
				</a>

				<li>
					<div class="todo-icon fui-plus-circle"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Extras</strong>
						</h4>
						Tu equipo y más detalles
					</div>
				</li>

				<a class="no-link" href="{%url 'dash:rewards' project.pk%}">
				<li>
					<div class="todo-icon fui-heart"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Recompensas</strong>
						</h4>
						¡Motiva a tu audiencia!
					</div>
				</li>
				</a>

				<li>
					<div class="todo-icon fui-upload"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Documentos</strong>
						</h4>
						Sube tus documentos
					</div>
				</li>

				<a class="no-link" href="{%url 'dash:chat'%}">
				<li>
					<div class="todo-icon fui-bubble"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Mensajes</strong>
						</h4>
						Comunicate con tus patrocinadores
					</div>
				</li>
				</a>

			</ul>
		</div>
		</div>




		

		<div class="col-md-6 col-md-offset-1">
				

				<form id="nuevo" class="row panel panel-default" action="." method="post">
				{%csrf_token%}
					<div class="col-md-6 col-md-offset-3 panel-body">

					<div class="row">
					<h4 class="col-md-12">
						¿Cómo se llama tu proyecto?
					</h4>
					<input {%if project.publish%}disabled{%endif%} value="{{project.name}}" name="name" required placeholder="Mi fabuloso proyecto" class="form-control input-hg col-md-12" type="text">
					</div>

					<div class="row">
					<h4 class="col-md-12">
						¿Cuanto dinero necesitas?
					</h4>
					<div class="input-group">
					  <span class="input-group-addon">$</span>
					  <input {%if project.publish%}disabled{%endif%}  value="{{project.goal}}" name="goal" required type="number" class="form-control input-hg" placeholder="200000" />
					</div>
					</div>

					<div class="row">
					<h4 class="col-md-12">
						¿En que categoría encaja?
					</h4>
						
						<select name="tags" class="form-control select select-danger select-block mbl">
						  <optgroup label="Categorias">
						  	{%for c in cats%}
						    <option {%if project.tags.all.0.name == c.name%} selected {%endif%} value="{{c.name}}">
						    	{{c.name}}
						    </option>
						    {%endfor%}
						  </optgroup>
						</select>

					</div>

					<br>
					<input {%if project.publish%}disabled{%endif%}  class="btn btn-hg btn-success" type="submit" value="Guardar">

					</div> <!-- offset-->

			</form>


		

		</div>
	</article>



</section>



<script>
	$("select").select2({dropdownCssClass: 'dropdown-inverse'});
</script>

{%endblock content%}

dashboard/templates/dashboard/dash.html
{%extends 'base.html'%}
{%load static%}
{%load dash_tags%}

{%block content%}
{%count_projects as nums %}


<section class="contendor centrado">

	<h3 class="demo-panel-title">{{project}} / {{section}}</h3>

	<article class="row">

		<div class="col-md-3 col-md-offset-1">
			<div class="todo">
			
			<ul>

				<a class="no-link" href="{%url 'dash:detail' project.pk%}">
				<li class="todo-done">
					
					<div class="todo-icon fui-resize"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Dashboard</strong>
						</h4>
						¿Cómo va tu proyecto?
					</div>
					
				</li>
				</a>

				<a class="no-link" href="{%url 'dash:basics' project.pk%}">
				<li >
					
					<div class="todo-icon fui-eye"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Info Basica</strong>
						</h4>
						Empezamos por aquí
					</div>
					
				</li>
				</a>

				<a class="no-link" href="{%url 'dash:history' project.pk%}">
				<li>
					
					<div class="todo-icon fui-image"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Descripción</strong>
						</h4>
						Cuentanos tu historia
					</div>
					
				</li>
				</a>

				<li>
					<div class="todo-icon fui-plus-circle"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Extras</strong>
						</h4>
						Tu equipo y más detalles
					</div>
				</li>

				<a class="no-link" href="{%url 'dash:rewards' project.pk%}">
				<li>
					<div class="todo-icon fui-heart"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Recompensas</strong>
						</h4>
						¡Motiva a tu audiencia!
					</div>
				</li>
				</a>

				<li>
					<div class="todo-icon fui-upload"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Documentos</strong>
						</h4>
						Sube tus documentos
					</div>
				</li>

				<a class="no-link" href="{%url 'dash:chat'%}">
				<li>
					<div class="todo-icon fui-bubble"></div>
					<div class="todo-content">
						<h4 class="todo-name">
							<strong>Mensajes</strong>
						</h4>
						Comunicate con tus patrocinadores
					</div>
				</li>
				</a>

			</ul>
		</div>
		</div>




		

		<div class="col-md-6 col-md-offset-1">
			<article class="row">
				<div class="panel col-sm-6">
					<canvas id="myChart" width="400" height="400"></canvas>
				</div>

				<div class="panel col-sm-6">
					<canvas id="myChart2" width="400" height="400"></canvas>
				</div>
				

			</article>

			<article class="row">

				<div class="panel col-sm-6">
					<canvas id="myChart3" width="400" height="400"></canvas>
				</div>

				<div class="panel col-sm-6">
					<canvas id="myChart5" width="400" height="400"></canvas>
				</div>

				

			</article>
				
			
			<article class="row">

				<div class="well col-xs-12">
					<button class="btn btn-warning">
						<i class="fa fa-share-square-o" aria-hidden="true"></i>
						Enviar avanze a patrocinadores
					</button>
					<button class="btn btn-danger">
						<i class="fa fa-trash" aria-hidden="true"></i>
						Eliminar proyecto
					</button>
				</div>

			</article>
		</div>
	</article>



</section>



<script src="{%static 'bower_components/chart.js/dist/Chart.js'%}"></script>
<script>
    var ctx = $('#myChart');
    var myChart = new Chart(ctx,{
    	type: 'bar',
    data: {
        labels: ["Semana1", "Semana2", "Semana3", "Semana4", "Semana5", "Semana6"],
        datasets: [{
            label: 'Cantidad vs Semana',
            data: [1200, 1900, 300, 500, 200, 300],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },

    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }

    });
</script>

<script>
    var ctx = $('#myChart2');
    var myChart = new Chart(ctx,{
    	type: 'line',
    data: {
        labels: ["Semana1", "Semana2", "Semana3", "Semana4", "Semana5", "Semana6"],
        datasets: [{
            label: 'Cantidad vs Semana',
            data: [1200, 1900, 300, 500, 200, 300],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },

    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }

    });
</script>

<script>
    var ctx = $('#myChart3');
    var myChart = new Chart(ctx,{
    	type: 'radar',
    data: {
        labels: ["Semana1", "Semana2", "Semana3", "Semana4", "Semana5", "Semana6"],
        datasets: [{
            label: 'Cantidad vs Semana',
            data: [1200, 1900, 300, 500, 200, 300],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },

    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }

    });
</script>


<script>
    var ctx = $('#myChart5');
    var myChart = new Chart(ctx,{
    	type: 'pie',
    data: {
        labels: ["Semana1", "Semana2", "Semana3", "Semana4", "Semana5", "Semana6"],
        datasets: [{
            label: 'Cantidad vs Semana',
            data: [1200, 1900, 300, 500, 200, 300],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },

    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }

    });
</script>



{%endblock content%}

dashboard/templates/dashboard/extra.html
{%extends 'dashboard/dash.html'%}

{%block segundo%}
<div class="espacio"></div>

<section class="row">

<form id="basics-form" action="." method="post" enctype="multipart/form-data">
	{%csrf_token%}






<article class="large-8 columns">

<div class="card">


<label>
	<h3>Titulo de la recompensa</h3>
	¿Cual es el título de la ecompensa?
	<input name="name" type="text" value="">
</label>


<div class="espacio"></div>


<label>
	<h3>Descripción de la recompensa</h3>
	¿De qué trata tu recompensa?
	<textarea name="desc" type="text" ></textarea>
</label>


<div class="espacio"></div>


<label>
	<h3>Monto para tener acceso a la recompensa</h3>
	¿Cuanto dinero requiere tu recompensa?
	<input name="goal" type="number" step="1000" min="0" value="">
</label>

<div class="espacio"></div>


</div> <!--card-->


</article>

<article class="large-4 columns">


<div class="card">
<label>
	<h3>Imagen de la recompensa</h3>
	¿Cual es la imagen de tu recompensa?
	<input id="img" name="img" type="file" value="{{project.img}}">
	{% if project.img %}
	<img id="preview" src="{{project.img.url}}">
	{%else%}
	<img id="preview" src="">
	{%endif%}
</label>
</div>



</article>





</form>

</section>





























<script>

$('#guardar').on('click',function(){

	$('#basics-form').submit();

});



</script>

{%endblock segundo%}

dashboard/templates/dashboard/perfil.html
{%extends 'base.html'%}

{%block content%}

<section class="contendor centrado">

	<h3>Bienvenido {{request.user.username}}</h3>

	<article class="row">

		<div class="col-md-4 col-md-offset-4 panel panel-default">

			<div class="panel-body">

				
					
				{%if not request.user.profile.img%}
				<img class="img_perfil redonda" width="200" src="https://cdn3.iconfinder.com/data/icons/rcons-user-action/32/girl-512.png" data-toggle="tooltip" title="Subir nueva imagen">
				{%else%}
				<img class="img_perfil redonda" width="200" src="{{request.user.profile.img.url}}" data-toggle="tooltip" title="Subir nueva imagen">
				{%endif%}
				

				<br><br><h5 class="">{{request.user.email}}</h5>

				
				<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
				  Completa tus datos
				</button>

				<div class="collapse" id="collapseExample">
					<br>
				  <div class="well">
				    
				    <form id="imagen" action="." method="post" enctype="multipart/form-data">
						{%csrf_token%}

						{%if request.user.profile.tel%}
						<span>Tu Teléfono</span>
					  	<input value="{{request.user.profile.tel}}" placeholder="Tu teléfono" class="form-control" name="tel" type="text">

					  	<span>Tu Edad</span>
					  	<input value="" placeholder="Tu Edad" class="form-control" name="edad" type="text">


					  	{%else%}
					  	<input placeholder="Tu telefono" class="form-control" name="tel" type="text">
					  	{%endif%}

					  	<input name="img" id="file" style="display:none" type="file">

					  	<br>
					  	<input class="btn btn-inverse" type="submit" value="guardar">
					</form>

				  </div>
				</div>



				
					
			</div>
		</div>

	</article>

	<article class="row">

		<h4>Tus proyectos:</h4>

		<div class="col-md-4 col-md-offset-4">

			<div class="panel-body">
				<div class="list-group">
				  	{%for p in request.user.projects.all%}
				  	<a href="{{p.get_absolute_url}}" class="list-group-item">
					    <h6 class="list-group-item-heading">{{p.name}}</h6>
					    <div class="progress">
						  <div class="progress-bar progress-bar-success" style="width: 10%;"></div>		 
						</div>
					</a>
					    {%empty%}
					    <a href="{%url 'projects:new'%}" class="list-group-item list-group-item-danger">aún no haz publicado proyectos</a>

				    {%endfor%}
				  
				</div>

			</div>
		</div>

	</article>



</section>




<script type="text/javascript">

  function readURL(input) {



    if (input.files && input.files[0]) {
        var reader = new FileReader();


        reader.onload = function (e) {
            $('.img_perfil').attr('src', e.target.result);
            // Extra para actualizar la img
            $('#imagen').submit();

        }

        reader.readAsDataURL(input.files[0]);
    }
}

  function readVideo() {

    $('#vidPrev').attr('src',$('#vid').val());
    
    }


// $("#file").change(function(){
//     readURL(this);
// });

// $('#vid').change(function(){

//     readVideo();
// })


$('img').on('click',function(){
	$('#file').click();

});
$("#file").change(function(){

    readURL(this);
    

});

</script>

{%endblock content%}

dashboard/templates/dashboard/projects_list.html
{%extends 'base.html'%}
{%load static%}

{%block content%}

<section class="section row">

	<div class="espacio"></div>

	<div class="card large-4 large-centered columns">
		<img  src="{%if request.user.profile.img %}{{request.user.profile.img.url}}{%else%}{%static 'images/clas.jpg'%}{%endif%}">
		<!--<h4>{{request.user.username}}</h4>
		<p>{{request.user.email}}</p>-->
		<div class="container">
			<a href="/accounts/profile" class="card-button">Editar Perfil</a>
			<a class="card-button">Cambiar contraseña</a>
		</div>
	</div>
	<div class="espacio"></div>
	<div class="card large-4 large-centered columns">
		<h5>PROYECTOS CREADOS:</h5>
		<ul>
			<!--<li>
				<span>FixterGeek</span>
				<i class="fa fa-check-circle" aria-hidden="true"></i>

			</li>
			<li>
				<span>Hackatón</span>
				<i style="color:orange" class="fa fa-minus-circle" aria-hidden="true"></i>


			</li>-->
			{%for p in projects%}
			<li>
				<a href="{%url 'dash:detail' p.pk%}">
				<span>{{p.name}}</span>
				<i class="fa fa-check-circle" aria-hidden="true"></i>
				</a>
			{%empty%}
			<span>No hay Proyectos Homs</span>
				<i class="fa fa-star-half-o" aria-hidden="true"></i>
			</li>
			{%endfor%}
		</ul>
	</div>



</section>

{%endblock content%}