cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns=[
	url(r'^$', views.Detalle.as_view(),name="cart_detail"),
	url(r'^add/(?P<pk>\d+)/$', views.Agregar.as_view(), name="cart_add"),
	url(r'^remove/(?P<pk>\d+)/$', views.Remove.as_view(), name="cart_remove")
	
]

dashboard/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

	url(r'^$',
		views.Dash.as_view(),
		name="dash"),

	url(r'^(?P<pk>\d+)/rewards/$',
		views.Rewards.as_view(),
		name="rewards"),

	url(r'^(?P<pk>\d+)/$',
		views.Detail.as_view(),
		name="detail"),

	url(r'^support/$',
		views.Support.as_view(),
		name="support"),

	url(r'^(?P<pk>\d+)/basics/$',
		views.Basics.as_view(),
		name="basics"),

	url(r'^(?P<pk>\d+)/history/$',
		views.History.as_view(),
		name="history"),

	url(r'^(?P<pk>\d+)/team/$',
		views.Team.as_view(),
		name="team"),

	url(r'^(?P<pk>\d+)/extra/$',
		views.Extra.as_view(),
		name="extra"),

	url(r'^chat/$',
		views.Chating.as_view(),
		name="chat"),
]

projects/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	
	url(r'^json/(?P<pk>\d+)/$',
		views.JsonRewards.as_view(),
		name="json_rewards"),

	url(r'^explorar/(?P<cat>[-\w]+)/$',
		views.Explorar.as_view(),
		name="categoria"),

	url(r'^explorar/$',
		views.Explorar.as_view(),
		name="explorar"),

	url(r'^new/$',
		views.NewProject.as_view(),
		name="new"),
    
    url(r'^(?P<pk>\d+)/$', 
    	views.DetailProject.as_view(), 
    	name='detail'),
    
    url(r'^$', 
    	views.Projects.as_view(), 
    	name='list'),
    ]

retozapopan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import urls as accountsURLs
from social.apps.django_app import urls as socialURLs
# from social_django import urls as socialURLs
from main import urls as mainUrls
from inputs import urls as inputsURLs
from dashboard import urls as dashboardURLs
from projects import urls as projectsURLs
from cart import urls as cartURLs

from django.views.static import serve
from django.conf import settings


urlpatterns = [

    #main
    url(r'^', include(mainUrls)),

    url(r'^inputs/',
        include(inputsURLs)),

    url(r'^dashboard/',
        include(dashboardURLs, namespace="dash")),

    url(r'^projects/',
        include(projectsURLs, namespace="projects")),

    url(r'^accounts/',
        include(accountsURLs)),

    url(r'^cart/',
        include(cartURLs, namespace="cart")),

    #Django Admin
    url(r'^admin/', admin.site.urls),

    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs={'document_root':settings.MEDIA_ROOT}
        ),

    # Social Auth
    url('social-auth/',
        include(socialURLs,
            namespace="social")),

]

templates/base.html
{%load static%}
{%load form_tags%}
<!DOCTYPE html>
<html>

<head>
  <title>CrowdPopan</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- flat ui-->
<script src="{% static 'js/flat-ui.min.js' %}"></script>
<!-- bootstrap-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>



<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">


    <!-- Fa fa icons-->
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- foundation -->
    <!--
    <link rel="stylesheet" type="text/css" href="{%static '/css/foundation.css'%}">
    -->

    <!-- Flat ui -->
    <link rel="stylesheet" href="{% static 'css/flat-ui.min.css' %}">

    <!-- custom -->
  <link rel="stylesheet" type="text/css" href="{%static '/css/app.css'%}">


    <!--

    <link rel="stylesheet" href="{% static '/bower_components/chartist/dist/chartist.css' %}">

    <style>
      .top-bar-right{
        padding-top: 1%;
      }
    </style>

    -->

</head>
<body>

  <div class="carga"></div>


<!--Responsive nav-->


<nav class="navbar navbar-inverse navbar-embossed" role="navigation">
 <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <a class="navbar-brand" href="{%url 'home'%}">CrowdZ</a>
  </div>
  <div class="collapse navbar-collapse" id="navbar-collapse-01">
    <ul class="nav navbar-nav">
      <li {%if nav_section == 'explorar' %} class="active" {%endif%} ><a href="{%url 'projects:categoria' 'prro'%}">Explorar</a></li>
      <li {%if nav_section == 'new' %} class="active" {%endif%} ><a href="{%url 'projects:new'%}">Publica tu Proyecto</a></li>
    </ul>

    {%if nav_section == "explorar"%}
    <form class="navbar-form navbar-left" action="#" role="search">
      <div class="form-group">
        <div class="input-group">
          <input class="form-control" id="navbarInput-01" type="search" placeholder="Search">
          <span class="input-group-btn">
            <button type="submit" class="btn"><span class="fui-search"></span></button>
          </span>
        </div>
      </div>
    </form>


    {%endif%}

    {%if request.user.is_authenticated%}

         <!--Cart-->
        <ul class="nav navbar-nav">
          <li data-toggle="tooltip" data-placement="bottom" title="Tienes un patrocinio pendiente">


            {%with total_items=cart|length%}
            {%if cart|length > 0%}
            <a href="{%url 'cart:cart_detail'%}">
              <i class="fa fa-money" aria-hidden="true"></i>
              <span class="navbar-new">
                 {{total_items}}
              </span>
             

            </a>
            {%else%}
            <i class="fa fa-money" aria-hidden="true"></i>
            {%endif%}
            {%endwith%}

              

          </li>
        </ul> <!--cart-->

    {%endif%}



      <div class="navbar-right">
        {%if request.user.is_authenticated%}

        <!--badges-->
        <ul class="nav navbar-nav">
          <li data-toggle="tooltip" data-placement="bottom" title="Tienes mensajes pendientes">
            <a href="{%url 'dash:chat'%}">
              <span class="fui-mail"></span>
              <!-- Indicator with number -->
              <span class="navbar-new">2</span>
            </a>
          </li>
        </ul>
        
        
        <!-- Inverted skin  -->
        <div class="btn-group">
          <button class="btn btn-inverse navbar-btn dropdown-toggle" type="button" data-toggle="dropdown">
            {{request.user.username}} <span class="caret"></span>
          </button>
          <ul class="dropdown-menu dropdown-menu-inverse" role="menu">
            <li><a href="{%url 'dash:dash'%}">PERFIL</a></li>
            <li class="dropdown-header">Tus proyectos</li>
            {%for p in request.user.projects.all%}
            <li><a href="{{p.get_absolute_url}}">{{p.name}}</a></li>
            {%endfor%}
            <li class="divider"></li>
            <li><a href="{%url 'logout'%}">Cerrar Sesion</a></li>
          </ul>
        </div>


        {%else%}
      <a href="{%url 'signup'%}" class="btn btn-warning btn-xs" type="button">SignUp</a>
      <a href="{%url 'login'%}" class="btn btn-default navbar-btn btn-xs" type="button">Sign in</a>

      {%endif%}

      </div>

  </div><!-- /.navbar-collapse -->
</nav>

<!--Responsive nav-->


<!-- Mensajes-->
{% if messages %}

    {% for message in messages %}

    <div class="centrado alert alert-{% if message.tags == 'success'%}success{%else%}danger{%endif%}" role="alert">{{ message }}</div>

    {% endfor %}

{% endif %}




<!--Firebase-->

<script src="https://www.gstatic.com/firebasejs/3.6.4/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "AIzaSyAafI7wItZtcja5k_60SGLq1VYC5WVOzYI",
    authDomain: "rzapopan-5f227.firebaseapp.com",
    databaseURL: "https://rzapopan-5f227.firebaseio.com",
    storageBucket: "rzapopan-5f227.appspot.com",
    messagingSenderId: "381015477211"
  };
  firebase.initializeApp(config);
</script>



<!--<script src="{%static '/js/vendor/foundation.js'%}"></script>-->

{% block content%}
{% endblock content%}








<!--
<script src="{%static '/js/vendor/what-input.js'%}"></script>
<script src="{%static '/js/app.js'%}"></script>
-->



<!--
<script src="{%static '/bower_components/chartist/dist/chartist.js'%}"></script>
-->

<script type="text/javascript">

//   function readURL(input) {

//     if (input.files && input.files[0]) {
//         var reader = new FileReader();

//         reader.onload = function (e) {
//             $('#preview').attr('src', e.target.result);
//         }

//         reader.readAsDataURL(input.files[0]);
//     }
// }

//   function readVideo() {

//     $('#vidPrev').attr('src',$('#vid').val());
    
//     }


// $("#img").change(function(){
//     readURL(this);
// });

// $('#vid').change(function(){



$('.carousel').carousel()

//     readVideo();
// })

</script>

<script type="text/javascript">
            // Wait for window load
    $(window).on('load',function() {
        // Animate loader off screen
        $(".carga").fadeOut("slow");
    });


    $('[data-toggle="tooltip"]').tooltip()
</script>

{%block scripts%}
{%endblock scripts%}



</body>
</html>

templates/pagination.html
<div>
  <ul class="pagination pagination-success">
  	{%if page.has_previous%}
    <li class="previous">
      <a href="?page={{page.previous_page_number}}" class="fui-arrow-left"></a>
    </li>
    {%endif%}


        <li>
          Pagina {{page.number}} de {{page.paginator.num_pages}}
        </li>

        
       
      


    {%if page.has_next%}
    <li class="next">
      <a href="?page={{page.next_page_number}}" class="fui-arrow-right"></a>
    </li>
    {%endif%}
  </ul>
</div>